CASSANDRA-17295: Make vtables accessible via internode messaging
apache/cassandra pull request #1429
Opened 2022-01-26 18:43 UTC by dcapwell

2022-01-26 18:46 UTC, dcapwell commented on src/java/org/apache/cassandra/db/virtual/AbstractVirtualTable.java
> +                                .id(TableId.forSystemTable(metadata.keyspace, metadata.name))
needed to make consistent cross-cluster

2022-01-26 21:14 UTC, dcapwell commented on src/java/org/apache/cassandra/cql3/QueryProcessor.java
> +    public static Future<UntypedResultSet> execute(InetAddressAndPort address, String query, Object... values)
the reason for async is so repair can submit and deal with when complete; rather than block waiting.

2022-01-26 21:17 UTC, dcapwell commented on src/java/org/apache/cassandra/cql3/QueryProcessor.java
> +                                select.processPartition(partition, options, result, nowInSec);
was wondering if we should pull this into a util; PartitionIterator -> ResultSet is specific to SelectStatement

2022-02-04 17:47 UTC, iamaleksey requested changes
Good quality plumbing, and I appreciate the removal or those virtual query classes. My only change request is to assign a deterministic UUID to `TableMetadata` in the constructor, based on `VIRTUAL` `Kind`, rather than based on key space name. As a side effect, we would still be allowing arbitrarily named virtual key spaces with little hassle to implementors, and won't need to modify existing unit tests as much.

2022-02-04 17:47 UTC, iamaleksey commented on src/java/org/apache/cassandra/db/virtual/AbstractVirtualTable.java
> +                                .id(TableId.forSystemTable(metadata.keyspace, metadata.name))
Would probably be nicer if we gave virtual tables deterministic ids from the very beginning, via `TableMetadata.Builder#build()`?

2022-02-04 17:47 UTC, iamaleksey commented on src/java/org/apache/cassandra/db/PartitionRangeReadCommand.java
> +                                                             trackWarnings);
I think we generally prefer to wrap multiline statement bodies like that in curly braces. I don't mind either way, but would prefer to change the style here and elsewhere across the PR (here and in `SinglePartitionReadCommand`).

2022-02-04 17:47 UTC, iamaleksey commented on src/java/org/apache/cassandra/db/PartitionRangeReadCommand.java
> +        private VirtualTablePartitionRangeReadCommand(boolean isDigest, int digestVersion, boolean acceptsTransient, TableMetadata metadata, int nowInSec, ColumnFilter columnFilter, RowFilter rowFilt
Formatting nit: gone a bit long here.

2022-02-04 19:36 UTC, dcapwell commented
pushed changes based off feedback

2022-02-08 10:43 UTC, iamaleksey approved these changes
Looking great now, +1.

2022-03-16 07:33 UTC, closed without merging