CASSANDRA-16555 - Add out-of-the-box snitch for Ec2 IMDSv2 (new PR)
apache/cassandra pull request #1587
Opened 2022-04-25 13:03 UTC by paulrutter

New PR since the original branch for https://github.com/apache/cassandra/pull/949 was removed.

2022-04-25 13:06 UTC, paulrutter commented on src/java/org/apache/cassandra/locator/Ec2MultiRegionSnitchIMDSv2.java
> +        DatabaseDescriptor.setBroadcastAddress(localPublicAddress);
@driftx this is the same as in the original snitch: https://github.com/blueconic/cassandra/blob/cassandra-2.2/src/java/org/apache/cassandra/locator/Ec2MultiRegionSnitch.java#L53

So we left it the same.

2022-04-25 13:19 UTC, paulrutter commented on src/java/org/apache/cassandra/locator/Ec2SnitchIMDSv2.java
> +        finally
The original doesn't do this, so we left this the same: https://github.com/blueconic/cassandra/blob/trunk/src/java/org/apache/cassandra/locator/Ec2Snitch.java#L104

2022-07-27 08:26 UTC, conradkleinespel commented
I'm also interested in seeing this merged. Let me know if there is anything I can do to help.

2022-12-29 09:07 UTC, jacek-lewandowski requested changes
Overall looks good. For trunk I'd consider refactoring it a bit though

2022-12-29 09:07 UTC, jacek-lewandowski commented on src/java/org/apache/cassandra/locator/Ec2SnitchIMDSv2.java
> +            final int cl = conn.getContentLength();
Could you extract this content reading code into some method maybe in `EC2Snitch` or somewhere else and then, use there and in the legacy EC2 snitch impl? (only for trunk)

Also, would be good to cover the case where content length is returned -1, and read the whole input stream then (or read the whole input stream always, for example using `ByteStreams.toByteArray`)

2022-12-29 09:07 UTC, jacek-lewandowski commented on src/java/org/apache/cassandra/locator/Ec2SnitchIMDSv2.java
> +    private static final long REFRESH_TOKEN_TIME = 21600;
The documentation says that it is the maximum TTL for the token - would be good to let the user configure that time using snitch properties (please remember to include the unit suffix in property name)

2022-12-29 09:07 UTC, jacek-lewandowski commented on src/java/org/apache/cassandra/locator/Ec2SnitchIMDSv2.java
> +        if (myToken == null || myLastTokenTime == null
nit: perhaps you can use `Suppliers.memoizeWithExpiration` to automatically control token lifetime

2022-12-29 09:07 UTC, jacek-lewandowski commented on src/java/org/apache/cassandra/locator/Ec2MultiRegionSnitchIMDSv2.java
> +        super();
nit: redundant

2022-12-29 09:07 UTC, jacek-lewandowski commented on src/java/org/apache/cassandra/locator/Ec2SnitchIMDSv2.java
> +    public Ec2SnitchIMDSv2() throws IOException, ConfigurationException
This constructor alone is redundant. You should add a constructor which takes `SnitchProperties` so that both are justified

2022-12-29 09:07 UTC, jacek-lewandowski commented on src/java/org/apache/cassandra/locator/Ec2SnitchIMDSv2.java
> +    private static final String TOKEN_ENDPOINT = "http://169.254.169.254/latest/api/token";
The endpoint IP is common for all of the addressed used here and in other EC2 classes. Would be good to extract it into a single field in `Ec2Snitch` class. If it was additionally configurable via `SnitchProperties` those classes would be more testable as we could simulate the EC2 endpoint (applies only for PR against trunk)

2022-12-29 09:07 UTC, jacek-lewandowski commented on src/java/org/apache/cassandra/locator/Ec2MultiRegionSnitchIMDSv2.java
> +    public Ec2MultiRegionSnitchIMDSv2() throws IOException, ConfigurationException
Similar to `Ec2SnitchIMDSv2` - please add a constructor accepting `SnitchProperties`

2023-06-28 14:57 UTC, closed without merging